<a href="https://colab.research.google.com/github/S-ArunaDevi06/aruna_hope_spech_detection/blob/main/hope_speech_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline
from sklearn import metrics

data=pd.read_csv("/content/drive/MyDrive/training_t1_sp.csv")
print(data)
data.head()
#data.describe()


#categories
categories=['hs','nhs']
x=data['text']
y=data['category']
train_x,test_x,train_y,test_y=train_test_split(x,y,train_size=0.7,random_state=42)
print(train_x)
print("train_y:\n",train_y)

model=make_pipeline(TfidfVectorizer(),MultinomialNB())
model.fit(train_x,train_y)
pred=model.predict(test_x)
print(metrics.accuracy_score(test_y,pred))

                       id                                               text  \
0     1409573191098511365  Si quieres saber lo diverso e inclusivo que es...   
1     1413030472020631553  Y ya esta ya me he liberado.Es que las injusti...   
2     1409489246608560128  me molesta mucho el discurso ese en favor del ...   
3     1412169304372568070   Yo te lo explico.No se pueden cortar las vías...   
4     1410109561814622210  8. No somos opositores al movimiento #LGTBI+, ...   
...                   ...                                                ...   
1395  1409474601831309317  Hoy es el día del Orgullo y tengo mil razones ...   
1396  1414347745427697667   Y sí, señores. Muchas veces la gente lgtb sal...   
1397  1409797952860721153   Un fuerte abrazo desde Andalucía y nuestras f...   
1398  1411689668433829890   Se siguen perdiendo oportunidades en materia ...   
1399  1409493212406988802  En el día del #OrgulloLGTBI reporta la  que en...   

     category  
0         nhs  
1      

In [ ]:
def predict_category(sentence,model=model):
  pred=model.predict(sentence)
  print(pred)

predict_category(['Uy de que mala ostia estoy hoy'])
predict_category(['La #LeyTrans ya #EsLey 😃, no es el paso definitivo pero si un gran paso. Gracias a x dar la batalla. Pienso en q hoy no es diputada en Madrid x hacerlo desde dentro en el, q han dilapidado años d compromiso #LGTBI por gente como'])

['nhs']
['hs']


In [ ]:
import pandas as pd
import numpy
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import SGDClassifier
from sklearn.pipeline import make_pipeline
from sklearn import metrics

data=pd.read_csv("/content/drive/MyDrive/training_t1_sp.csv")
print(data)
data.head()
#data.describe()


#categories
categories=['hs','nhs']
x=data['text']
y=data['category']
train_x,test_x,train_y,test_y=train_test_split(x,y,train_size=0.7,random_state=42)
print(train_x)
print("train_y:\n",train_y)

model=make_pipeline(TfidfVectorizer(),SGDClassifier(random_state=42))
model.fit(train_x,train_y)
pred=model.predict(test_x)
print(metrics.accuracy_score(test_y,pred))

                       id                                               text  \
0     1409573191098511365  Si quieres saber lo diverso e inclusivo que es...   
1     1413030472020631553  Y ya esta ya me he liberado.Es que las injusti...   
2     1409489246608560128  me molesta mucho el discurso ese en favor del ...   
3     1412169304372568070   Yo te lo explico.No se pueden cortar las vías...   
4     1410109561814622210  8. No somos opositores al movimiento #LGTBI+, ...   
...                   ...                                                ...   
1395  1409474601831309317  Hoy es el día del Orgullo y tengo mil razones ...   
1396  1414347745427697667   Y sí, señores. Muchas veces la gente lgtb sal...   
1397  1409797952860721153   Un fuerte abrazo desde Andalucía y nuestras f...   
1398  1411689668433829890   Se siguen perdiendo oportunidades en materia ...   
1399  1409493212406988802  En el día del #OrgulloLGTBI reporta la  que en...   

     category  
0         nhs  
1      

In [ ]:
##implementing k-fold cross validation for MultiNomialNB
from sklearn.model_selection import KFold
import pandas as pd
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

data=pd.read_csv("/content/drive/MyDrive/training_t1_sp.csv")
x=data['text']
y=data['category']

accuracy1=[]
scores1=[]
precision1=[]
recall1=[]

accuracy2=[]
scores2=[]
precision2=[]
recall2=[]
#k-fold cross validation
fold=10
kf = KFold(n_splits=fold, shuffle=True, random_state=42)

#count vectorizer, tfidf with multinomialNB
vectorizer = CountVectorizer()
tfidf=TfidfVectorizer()
model1=MultinomialNB()
model2=MultinomialNB()

for train_i,test_i in kf.split(x):
  x_train=[x[i] for i in train_i]
  y_train=[y[i] for i in train_i]
  x_test=[x[i] for i in test_i]
  y_test=[y[i] for i in test_i]

  train_vect1=vectorizer.fit_transform(x_train)
  test_vect1=vectorizer.transform(x_test)

  train_vect2=tfidf.fit_transform(x_train)
  test_vect2=tfidf.transform(x_test)


  #fitting model
  model1.fit(train_vect1,y_train)
  yhat=model1.predict(test_vect1)

  acc= accuracy_score(y_test,yhat)
  accuracy1.append(acc)

  f_score=f1_score(y_test,yhat,pos_label='hs')
  scores1.append(f_score)

  precision=precision_score(y_test,yhat,pos_label='hs')
  precision1.append(precision)

  recall=recall_score(y_test,yhat,pos_label='hs')
  recall1.append(recall)

  model2.fit(train_vect2,y_train)
  yhat=model2.predict(test_vect2)

  acc=accuracy_score(y_test,yhat)
  accuracy2.append(acc)

  f_score=f1_score(y_test,yhat,pos_label='hs')
  scores2.append(f_score)

  precision=precision_score(y_test,yhat,pos_label='hs')
  precision2.append(precision)

  recall=recall_score(y_test,yhat,pos_label='hs')
  recall2.append(recall)


print("\nAVERAGE ACCURACY count vectorizer: ",np.mean(accuracy1))
print("\nAVERAGE F1 SCORE count vectorier: ",np.mean(scores1))
print("\nAVEARGE PRECISION SCORE count vectorizer: ",np.mean(precision1))
print("\nAVEARGE RECALL SCORE count vectorizer: ",np.mean(recall1))

print("\nAVERAGE ACCURACY tfidf: ",np.mean(accuracy2))
print("\nAVERAGE F1 SCORE tfidf: ",np.mean(scores2))
print("\nAVEARGE PRECISION SCORE tfidf: ",np.mean(precision2))
print("\nAVEARGE RECALL SCORE tfidf: ",np.mean(recall2))




AVERAGE ACCURACY count vectorizer:  0.8135714285714286

AVERAGE F1 SCORE count vectorier:  0.8139042789025396

AVEARGE PRECISION SCORE count vectorizer:  0.8011012823959621

AVEARGE RECALL SCORE count vectorizer:  0.8287048546546062

AVERAGE ACCURACY tfidf:  0.8035714285714285

AVERAGE F1 SCORE tfidf:  0.8088295421190514

AVEARGE PRECISION SCORE tfidf:  0.778666068197907

AVEARGE RECALL SCORE tfidf:  0.8424461511901565


MULTINOMIAL NB FOR SUBMISSION


In [ ]:
##implementing k-fold cross validation for MultiNomialNB
from sklearn.model_selection import KFold
import pandas as pd
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, f1_score

data=pd.read_csv("/content/drive/MyDrive/training_t1_sp.csv")
x=data['text']
y=data['category']

accuracy1=[]
scores1=[]

accuracy2=[]
scores2=[]
#k-fold cross validation
fold=10
kf = KFold(n_splits=fold, shuffle=True, random_state=42)

#count vectorizer, tfidf with multinomialNB
vectorizer = CountVectorizer()
tfidf=TfidfVectorizer()
model1=MultinomialNB()
model2=MultinomialNB()

for train_i,test_i in kf.split(x):

  #train_vect1=vectorizer.fit_transform(x_train)
  #test_vect1=vectorizer.transform(x_test)

  train_vect2=tfidf.fit_transform(x)

  #fitting model
  model2.fit(train_vect2,y)


test_data=pd.read_csv("/content/drive/MyDrive/hope_speech_testing.csv")
x=test_data['text']
test_x=tfidf.transform(x)
pred=[]
indices=x.index
print(x,indices)
predictions=model2.predict(test_x)
print(predictions)
for i in range(len(x)):
  pred.append([indices[i],predictions[i]])

print(pred)



0      iiiiii como amo a mis amigas soy totalmente ho...
1      ¿Qué necesidad tiene la gente de decirme que e...
2      si soy una inmigrante que legalmente puede vot...
3      Mis amigas :no soy lesbiana . Mis amigas borra...
4      🇦🇷🏳️‍⚧️La provincia de Buenos Aires  anunció e...
                             ...                        
395    Lo lamento mucho, cuanta rabia aquí estamos pa...
396    Oigan ahorita que lo pienso,cuando estaba más ...
397    🔍#Entrevista de  a , psicóloga, docente e inve...
398    Y seguimos con un racismo institucional muy gr...
399    'Puede ser una trampa'. El objetivo de esta in...
Name: text, Length: 400, dtype: object RangeIndex(start=0, stop=400, step=1)
['hs' 'hs' 'nhs' 'hs' 'hs' 'nhs' 'hs' 'nhs' 'nhs' 'hs' 'hs' 'nhs' 'nhs'
 'hs' 'nhs' 'nhs' 'hs' 'nhs' 'hs' 'hs' 'nhs' 'nhs' 'nhs' 'hs' 'nhs' 'hs'
 'nhs' 'nhs' 'hs' 'hs' 'nhs' 'nhs' 'hs' 'hs' 'hs' 'nhs' 'hs' 'nhs' 'hs'
 'hs' 'hs' 'nhs' 'hs' 'hs' 'hs' 'nhs' 'hs' 'hs' 'nhs' 'nhs' 'nhs' 'nhs'
 'nhs' 

In [ ]:
import csv

field=['id','category']

fpath='/content/drive/MyDrive/predictions.csv'

with open(fpath, 'w') as csvfile:

    csv_writer = csv.writer(csvfile)
    csv_writer.writerow(field)
    csv_writer.writerows(pred)


SGDCLASSIFIER

In [ ]:
##implementing k-fold cross validation for SGDClassifier
from sklearn.model_selection import KFold
import pandas as pd
import numpy as np
from sklearn.linear_model import SGDClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, f1_score
from sklearn.metrics import precision_score, recall_score

data=pd.read_csv("/content/drive/MyDrive/training_t1_sp.csv")
x=data['text']
y=data['category']

accuracy1=[]
scores1=[]
precision1=[]
recall1=[]

accuracy2=[]
scores2=[]
precision2=[]
recall2=[]
#k-fold cross validation
fold=10
kf = KFold(n_splits=fold, shuffle=True, random_state=42)

#count vectorizer, tfidf
vectorizer = CountVectorizer()
tfidf=TfidfVectorizer()
model1=SGDClassifier(random_state=42)
model2=SGDClassifier(random_state=42)

for train_i,test_i in kf.split(x):
  x_train=[x[i] for i in train_i]
  y_train=[y[i] for i in train_i]
  x_test=[x[i] for i in test_i]
  y_test=[y[i] for i in test_i]

  train_vect1=vectorizer.fit_transform(x_train)
  test_vect1=vectorizer.transform(x_test)

  train_vect2=tfidf.fit_transform(x_train)
  test_vect2=tfidf.transform(x_test)


  #fitting model
  model1.fit(train_vect1,y_train)
  yhat=model1.predict(test_vect1)

  acc= accuracy_score(y_test,yhat)
  accuracy1.append(acc)

  f_score=f1_score(y_test,yhat,pos_label='hs')
  scores1.append(f_score)

  precision=precision_score(y_test,yhat,pos_label='hs')
  precision1.append(precision)

  recall=recall_score(y_test,yhat,pos_label='hs')
  recall1.append(recall)

  model2.fit(train_vect2,y_train)
  yhat=model2.predict(test_vect2)

  acc=accuracy_score(y_test,yhat)
  accuracy2.append(acc)

  f_score=f1_score(y_test,yhat,pos_label='hs')
  scores2.append(f_score)

  precision=precision_score(y_test,yhat,pos_label='hs')
  precision2.append(precision)

  recall=recall_score(y_test,yhat,pos_label='hs')
  recall2.append(recall)



print("\nAVERAGE ACCURACY count vectorizer: ",np.mean(accuracy1))
print("\nAVERAGE F1 SCORE count vectorier: ",np.mean(scores1))
print("\nAVEARGE PRECISION SCORE count vectorizer: ",np.mean(precision1))
print("\nAVEARGE RECALL SCORE count vectorizer: ",np.mean(recall1))

print("\nAVERAGE ACCURACY tfidf: ",np.mean(accuracy2))
print("\nAVERAGE F1 SCORE tfidf: ",np.mean(scores2))
print("\nAVEARGE PRECISION SCORE tfidf: ",np.mean(precision2))
print("\nAVEARGE RECALL SCORE tfidf: ",np.mean(recall2))




AVERAGE ACCURACY count vectorizer:  0.7849999999999999

AVERAGE F1 SCORE count vectorier:  0.7781166836628778

AVEARGE PRECISION SCORE count vectorizer:  0.786693393047394

AVEARGE RECALL SCORE count vectorizer:  0.7738223012761205

AVERAGE ACCURACY tfidf:  0.8014285714285714

AVERAGE F1 SCORE tfidf:  0.80154158636938

AVEARGE PRECISION SCORE tfidf:  0.7932374742501149

AVEARGE RECALL SCORE tfidf:  0.811332006458343


In [ ]:
##implementing k-fold cross validation for Support vector machine
from sklearn.model_selection import KFold
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, f1_score
from sklearn.metrics import precision_score, recall_score

data=pd.read_csv("/content/drive/MyDrive/training_t1_sp.csv")
x=data['text']
y=data['category']

accuracy1=[]
scores1=[]
precision1=[]
recall1=[]

accuracy2=[]
scores2=[]
precision2=[]
recall2=[]
#k-fold cross validation
fold=10
kf = KFold(n_splits=fold, shuffle=True, random_state=42)

#count vectorizer, tfidf
vectorizer = CountVectorizer()
tfidf=TfidfVectorizer()
model1=SVC(kernel="rbf", gamma=0.5, C=1.0) #rbf==>allows non linear boundaries
model2=SVC(kernel="rbf", gamma=0.5, C=1.0)

for train_i,test_i in kf.split(x):
  x_train=[x[i] for i in train_i]
  y_train=[y[i] for i in train_i]
  x_test=[x[i] for i in test_i]
  y_test=[y[i] for i in test_i]

  train_vect1=vectorizer.fit_transform(x_train)
  test_vect1=vectorizer.transform(x_test)

  train_vect2=tfidf.fit_transform(x_train)
  test_vect2=tfidf.transform(x_test)


  #fitting model
  model1.fit(train_vect1,y_train)
  yhat=model1.predict(test_vect1)

  acc= accuracy_score(y_test,yhat)
  accuracy1.append(acc)

  f_score=f1_score(y_test,yhat,pos_label='hs')
  scores1.append(f_score)

  precision=precision_score(y_test,yhat,pos_label='hs')
  precision1.append(precision)

  recall=recall_score(y_test,yhat,pos_label='hs')
  recall1.append(recall)

  model2.fit(train_vect2,y_train)
  yhat=model2.predict(test_vect2)

  acc=accuracy_score(y_test,yhat)
  accuracy2.append(acc)

  f_score=f1_score(y_test,yhat,pos_label='hs')
  scores2.append(f_score)

  precision=precision_score(y_test,yhat,pos_label='hs')
  precision2.append(precision)

  recall=recall_score(y_test,yhat,pos_label='hs')
  recall2.append(recall)



print("\nAVERAGE ACCURACY count vectorizer: ",np.mean(accuracy1))
print("\nAVERAGE F1 SCORE count vectorier: ",np.mean(scores1))
print("\nAVEARGE PRECISION SCORE count vectorizer: ",np.mean(precision1))
print("\nAVEARGE RECALL SCORE count vectorizer: ",np.mean(recall1))


print("\nAVERAGE ACCURACY tfidf: ",np.mean(accuracy2))
print("\nAVERAGE F1 SCORE tfidf: ",np.mean(scores2))
print("\nAVEARGE PRECISION SCORE tfidf: ",np.mean(precision2))
print("\nAVEARGE RECALL SCORE tfidf: ",np.mean(recall2))



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defin


AVERAGE ACCURACY count vectorizer:  0.4757142857142857

AVERAGE F1 SCORE count vectorier:  0.28027401433623134

AVEARGE PRECISION SCORE count vectorizer:  0.36

AVEARGE RECALL SCORE count vectorizer:  0.4156349206349207

AVERAGE ACCURACY tfidf:  0.8057142857142857

AVERAGE F1 SCORE tfidf:  0.7917568818507332

AVEARGE PRECISION SCORE tfidf:  0.8424598541353531

AVEARGE RECALL SCORE tfidf:  0.7479881625269167


In [ ]:
##implementing k-fold cross validation for logistic regression
from sklearn.model_selection import KFold
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, f1_score
from sklearn.metrics import precision_score, recall_score

data=pd.read_csv("/content/drive/MyDrive/training_t1_sp.csv")
x=data['text']
y=data['category']

accuracy1=[]
scores1=[]
precision1=[]
recall1=[]

accuracy2=[]
scores2=[]
precision2=[]
recall2=[]
#k-fold cross validation
fold=10
kf = KFold(n_splits=fold, shuffle=True, random_state=42)

#count vectorizer, tfidf
vectorizer = CountVectorizer()
tfidf=TfidfVectorizer()
model1=LogisticRegression(random_state=42)
model2=LogisticRegression(random_state=42)

for train_i,test_i in kf.split(x):
  x_train=[x[i] for i in train_i]
  y_train=[y[i] for i in train_i]
  x_test=[x[i] for i in test_i]
  y_test=[y[i] for i in test_i]

  train_vect1=vectorizer.fit_transform(x_train)
  test_vect1=vectorizer.transform(x_test)

  train_vect2=tfidf.fit_transform(x_train)
  test_vect2=tfidf.transform(x_test)


  #fitting model
  model1.fit(train_vect1,y_train)
  yhat=model1.predict(test_vect1)

  acc= accuracy_score(y_test,yhat)
  accuracy1.append(acc)

  f_score=f1_score(y_test,yhat,pos_label='hs')
  scores1.append(f_score)

  precision=precision_score(y_test,yhat,pos_label='hs')
  precision1.append(precision)

  recall=recall_score(y_test,yhat,pos_label='hs')
  recall1.append(recall)

  model2.fit(train_vect2,y_train)
  yhat=model2.predict(test_vect2)

  acc=accuracy_score(y_test,yhat)
  accuracy2.append(acc)

  f_score=f1_score(y_test,yhat,pos_label='hs')
  scores2.append(f_score)

  precision=precision_score(y_test,yhat,pos_label='hs')
  precision2.append(precision)

  recall=recall_score(y_test,yhat,pos_label='hs')
  recall2.append(recall)



print("\nAVERAGE ACCURACY count vectorizer: ",np.mean(accuracy1))
print("\nAVERAGE F1 SCORE count vectorier: ",np.mean(scores1))
print("\nAVEARGE PRECISION SCORE count vectorizer: ",np.mean(precision1))
print("\nAVEARGE RECALL SCORE count vectorizer: ",np.mean(recall1))

print("\nAVERAGE ACCURACY tfidf: ",np.mean(accuracy2))
print("\nAVERAGE F1 SCORE tfidf: ",np.mean(scores2))
print("\nAVEARGE PRECISION SCORE tfidf: ",np.mean(precision2))
print("\nAVEARGE RECALL SCORE tfidf: ",np.mean(recall2))




AVERAGE ACCURACY count vectorizer:  0.8121428571428572

AVERAGE F1 SCORE count vectorier:  0.808026955434683

AVEARGE PRECISION SCORE count vectorizer:  0.8177974644511842

AVEARGE RECALL SCORE count vectorizer:  0.7997974551393099

AVERAGE ACCURACY tfidf:  0.8078571428571429

AVERAGE F1 SCORE tfidf:  0.797278272381105

AVEARGE PRECISION SCORE tfidf:  0.833400691019903

AVEARGE RECALL SCORE tfidf:  0.7655249442289789


FOR SUBMISSION


In [ ]:
##implementing k-fold cross validation for logistic regression
from sklearn.model_selection import KFold
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, f1_score


data=pd.read_csv("/content/drive/MyDrive/training_t1_sp.csv")
x=data['text']
y=data['category']

#k-fold cross validation
fold=10
kf = KFold(n_splits=fold, shuffle=True, random_state=42)

#count vectorizer, tfidf
tfidf=TfidfVectorizer()
model2=LogisticRegression(random_state=42)

for train_i,test_i in kf.split(x):

  train_vect2=tfidf.fit_transform(x)

  #fitting model
  model2.fit(train_vect2,y)



test_data=pd.read_csv("/content/drive/MyDrive/hope_speech_testing.csv")
x=test_data['text']
test_x=tfidf.transform(x)
pred=[]
indices=x.index
print(x,indices)
predictions=model2.predict(test_x)
print(predictions)
print(list(predictions).count('nhs'))
for i in range(len(x)):
  pred.append([indices[i],predictions[i]])

print(pred)


0      iiiiii como amo a mis amigas soy totalmente ho...
1      ¿Qué necesidad tiene la gente de decirme que e...
2      si soy una inmigrante que legalmente puede vot...
3      Mis amigas :no soy lesbiana . Mis amigas borra...
4      🇦🇷🏳️‍⚧️La provincia de Buenos Aires  anunció e...
                             ...                        
395    Lo lamento mucho, cuanta rabia aquí estamos pa...
396    Oigan ahorita que lo pienso,cuando estaba más ...
397    🔍#Entrevista de  a , psicóloga, docente e inve...
398    Y seguimos con un racismo institucional muy gr...
399    'Puede ser una trampa'. El objetivo de esta in...
Name: text, Length: 400, dtype: object RangeIndex(start=0, stop=400, step=1)
['hs' 'nhs' 'nhs' 'nhs' 'nhs' 'nhs' 'hs' 'nhs' 'nhs' 'hs' 'hs' 'nhs' 'nhs'
 'nhs' 'nhs' 'nhs' 'nhs' 'nhs' 'hs' 'hs' 'nhs' 'hs' 'nhs' 'nhs' 'nhs' 'hs'
 'nhs' 'nhs' 'hs' 'hs' 'nhs' 'nhs' 'nhs' 'hs' 'hs' 'nhs' 'nhs' 'nhs' 'hs'
 'nhs' 'nhs' 'nhs' 'nhs' 'nhs' 'nhs' 'nhs' 'hs' 'nhs' 'nhs' 'nhs' 'nhs'


In [ ]:
import csv

field=['id','category']

fpath='/content/drive/MyDrive/predictions.csv'

with open(fpath, 'w') as csvfile:

    csv_writer = csv.writer(csvfile)
    csv_writer.writerow(field)
    csv_writer.writerows(pred)

In [ ]:
pip install transformers torch

  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21

In [ ]:
import pandas as pd
import numpy as np
from transformers import BertTokenizer, BertForSequenceClassification
from sklearn.model_selection import train_test_split

data=pd.read_csv("/content/drive/MyDrive/training_t1_sp.csv")
x=data['text']
y=data['category']
given_labels=['hs','nhs']

train_x,test_x,train_y,test_y=train_test_split(x,y,train_size=0.7,random_state=42)

#IIC/bert-base-spanish-wwm-cased-ctebmsp
tokenizer = BertTokenizer.from_pretrained('dccuchile/bert-base-spanish-wwm-cased')
model = BertForSequenceClassification.from_pretrained('dccuchile/bert-base-spanish-wwm-cased')


inputs = tokenizer(list(train_x), padding=True, truncation=True, return_tensors="pt")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at dccuchile/bert-base-spanish-wwm-cased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
train_x.describe()

count                                                   979
unique                                                  979
top        pero si han sido cinco #RefugeesWelcome los q...
freq                                                      1
Name: text, dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder
from torch.utils.data import DataLoader
from transformers import AdamW

#labels=[1,0]
encoder=LabelEncoder()
encoder.fit(train_y)
labels=encoder.transform(train_y)

print(labels)

# Prepare DataLoader
dataset = list(zip(inputs["input_ids"], inputs["attention_mask"],labels))
loader = DataLoader(dataset, batch_size=30, shuffle=True)

# Optimizer
optimizer = AdamW(model.parameters(), lr=1e-5)

# Training loop
model.train()
for epoch in range(2):
    print("epoch ",epoch," has started")
    count=0
    for batch in loader:
        count+=1
        print("executing ",count," th time")
        input_ids, attention_mask, labels = batch
        outputs = model(input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
    print("epoch completed")


[1 1 0 1 1 0 1 1 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 1
 0 0 0 1 0 0 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 0 1 1 1 1 1 1 0
 1 0 1 0 1 1 1 0 1 1 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0 1 0 1 0 0 0 0 1 1 0 1 0
 0 1 1 1 0 1 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 1 1 0 1 1 0 0 0 1 1 1 1
 0 1 1 1 0 1 1 1 1 1 0 0 1 1 0 1 1 1 1 0 0 1 1 0 0 0 1 1 1 0 0 1 0 1 1 0 0
 1 1 0 1 1 1 0 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 1 0 1 1 0 0 1 1 0 1 1 0 0 1 1
 1 0 1 0 1 0 0 1 1 0 1 0 1 1 1 1 1 0 0 0 0 1 0 1 0 1 1 1 1 0 0 1 0 1 0 0 0
 0 0 0 1 0 1 1 0 0 1 0 1 0 0 1 1 0 1 0 1 1 1 0 0 1 1 0 0 1 0 0 0 1 0 1 0 1
 1 0 1 0 1 0 1 1 0 1 0 0 1 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 1 0 0 1 0 1 0 0 0
 1 1 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1
 1 0 1 0 1 1 0 0 1 1 0 0 0 0 1 1 1 0 0 1 1 1 0 0 1 1 1 0 0 1 1 1 1 1 0 1 1
 1 1 0 1 0 0 1 1 0 1 1 0 1 0 1 1 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 1 0 1 0
 0 1 0 0 1 1 0 1 0 0 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 1 0 1 0 1 0 1
 1 1 1 0 1 0 1 0 1 1 1 0 

/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:588: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


epoch  0  has started
executing  1  th time
executing  2  th time
executing  3  th time
executing  4  th time
executing  5  th time
executing  6  th time
executing  7  th time
executing  8  th time
executing  9  th time
executing  10  th time
executing  11  th time
executing  12  th time
executing  13  th time
executing  14  th time
executing  15  th time
executing  16  th time
executing  17  th time
executing  18  th time
executing  19  th time
executing  20  th time
executing  21  th time
executing  22  th time
executing  23  th time
executing  24  th time
executing  25  th time
executing  26  th time
executing  27  th time
executing  28  th time
executing  29  th time
executing  30  th time
executing  31  th time
executing  32  th time
executing  33  th time
epoch completed
epoch  1  has started
executing  1  th time
executing  2  th time
executing  3  th time
executing  4  th time
executing  5  th time
executing  6  th time
executing  7  th time
executing  8  th time
executing  9  

Index([ 665,  624,  115,  478,  233,  724,  208,  867,  939,  479,
       ...
       1026,  352,  124,  178,  287, 1349, 1163,  294, 1357, 1237],
      dtype='int64', length=421)
478


In [ ]:
from sklearn.metrics import accuracy_score
pred=[]
vals=[]
indices=test_x.index
for i in list(test_x):
  new_texts =i
  n=list(test_x).index(i)
  inputs = tokenizer(new_texts, padding=True, truncation=True, return_tensors="pt")

  logits = model(**inputs).logits
  predictions = logits.argmax(dim=1)
  print(predictions)
  if (predictions==0):
     pred.append([indices[n],'hs'])
     vals.append('hs')
  else:
     pred.append([indices[n],'nhs'])
     vals.append('nhs')
#accuracy = accuracy_score(test_y,pred)
#print(accuracy)
print(pred)
'''
if predictions.item()==0:
  print("hs")
else:
  print("nhs")
  '''

tensor([1])
tensor([1])
tensor([1])
tensor([0])
tensor([1])
tensor([0])
tensor([0])
tensor([1])
tensor([0])
tensor([0])
tensor([0])
tensor([0])
tensor([0])
tensor([0])
tensor([0])
tensor([1])
tensor([1])
tensor([1])
tensor([0])
tensor([0])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([0])
tensor([0])
tensor([0])
tensor([1])
tensor([0])
tensor([0])
tensor([1])
tensor([1])
tensor([0])
tensor([0])
tensor([0])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([0])
tensor([0])
tensor([0])
tensor([0])
tensor([1])
tensor([1])
tensor([0])
tensor([0])
tensor([1])
tensor([1])
tensor([0])
tensor([1])
tensor([1])
tensor([0])
tensor([0])
tensor([0])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([0])
tensor([0])
tensor([0])
tensor([1])
tensor([1])
tensor([0])
tensor([1])
tensor([0])
tensor([1])
tensor([1])
tensor([0])
tensor([0])
tensor([1])
tensor([1])
tens

'\nif predictions.item()==0:\n  print("hs")\nelse:\n  print("nhs")\n  '

In [ ]:
print(test_y)
indices=test_y.index
print(indices)

665     nhs
624     nhs
115     nhs
478      hs
233     nhs
       ... 
1349    nhs
1163    nhs
294     nhs
1357    nhs
1237    nhs
Name: category, Length: 421, dtype: object
Index([ 665,  624,  115,  478,  233,  724,  208,  867,  939,  479,
       ...
       1026,  352,  124,  178,  287, 1349, 1163,  294, 1357, 1237],
      dtype='int64', length=421)


In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score,recall_score
accuracy = accuracy_score(test_y,vals)
print("\nACCURACY: ",accuracy)
f1=f1_score(test_y,vals,pos_label='hs')
print("\nF1: ",f1)
precision=precision_score(test_y,vals,pos_label='hs')
print("\nPRECISION: ",precision)
recall=recall_score(test_y,vals,pos_label='hs')
print("\nRECALL: ",recall)


ACCURACY:  0.8147268408551069

F1:  0.7989690721649485

PRECISION:  0.8959537572254336

RECALL:  0.7209302325581395


In [ ]:
import csv

field=['id','category']

fpath='/content/drive/MyDrive/predictions.csv'

with open(fpath, 'w') as csvfile:

    csv_writer = csv.writer(csvfile)
    csv_writer.writerow(field)
    csv_writer.writerows(pred)


**TESTING**

In [ ]:
data=pd.read_csv("/content/drive/MyDrive/hope_speech_testing.csv")
x=data['text']
pred=[]
indices=x.index
print(x,indices)
for i in list(x):
  new_texts =i
  n=list(x).index(i)
  inputs = tokenizer(new_texts, padding=True, truncation=True, return_tensors="pt")

  logits = model(**inputs).logits
  predictions = logits.argmax(dim=1)
  print(predictions)
  if (predictions==0):
     pred.append([indices[n],'hs'])
  else:
     pred.append([indices[n],'nhs'])

0      iiiiii como amo a mis amigas soy totalmente ho...
1      ¿Qué necesidad tiene la gente de decirme que e...
2      si soy una inmigrante que legalmente puede vot...
3      Mis amigas :no soy lesbiana . Mis amigas borra...
4      🇦🇷🏳️‍⚧️La provincia de Buenos Aires  anunció e...
                             ...                        
395    Lo lamento mucho, cuanta rabia aquí estamos pa...
396    Oigan ahorita que lo pienso,cuando estaba más ...
397    🔍#Entrevista de  a , psicóloga, docente e inve...
398    Y seguimos con un racismo institucional muy gr...
399    'Puede ser una trampa'. El objetivo de esta in...
Name: text, Length: 400, dtype: object RangeIndex(start=0, stop=400, step=1)
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([0])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([0])
tensor([0])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([

In [ ]:
print()

20


In [ ]:
import csv

field=['id','category']

fpath='/content/drive/MyDrive/predictions.csv'

with open(fpath, 'w') as csvfile:

    csv_writer = csv.writer(csvfile)
    csv_writer.writerow(field)
    csv_writer.writerows(pred)


**TRANSFORMER 2**

In [ ]:
import pandas as pd
import numpy as np
from transformers import BertTokenizer, BertForSequenceClassification
from sklearn.model_selection import train_test_split

data=pd.read_csv("/content/drive/MyDrive/training_t1_sp.csv")
x=data['text']
y=data['category']
given_labels=['hs','nhs']

train_x,test_x,train_y,test_y=train_test_split(x,y,train_size=0.7,random_state=42)


tokenizer = BertTokenizer.from_pretrained('IIC/bert-base-spanish-wwm-cased-ctebmsp')
model1 = BertForSequenceClassification.from_pretrained('IIC/bert-base-spanish-wwm-cased-ctebmsp')


inputs = tokenizer(list(train_x), padding=True, truncation=True, return_tensors="pt")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/657 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/242k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/729k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.11k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/439M [00:00<?, ?B/s]

In [ ]:
from sklearn.preprocessing import LabelEncoder
from torch.utils.data import DataLoader
from transformers import AdamW

#labels=[1,0]
encoder=LabelEncoder()
encoder.fit(train_y)
labels=encoder.transform(train_y)

print(labels)

# Prepare DataLoader
dataset = list(zip(inputs["input_ids"], inputs["attention_mask"],labels))
loader = DataLoader(dataset, batch_size=30, shuffle=True)

# Optimizer
optimizer = AdamW(model1.parameters(), lr=1e-5)

# Training loop
model1.train()
for epoch in range(2):
    print("epoch ",epoch," has started")
    count=0
    for batch in loader:
        count+=1
        print("executing ",count," th time")
        input_ids, attention_mask, labels = batch
        outputs = model1(input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
    print("epoch completed")


[1 1 0 1 1 0 1 1 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 0 1
 0 0 0 1 0 0 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 0 1 1 1 1 1 1 0
 1 0 1 0 1 1 1 0 1 1 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0 1 0 1 0 0 0 0 1 1 0 1 0
 0 1 1 1 0 1 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 1 1 0 1 1 0 0 0 1 1 1 1
 0 1 1 1 0 1 1 1 1 1 0 0 1 1 0 1 1 1 1 0 0 1 1 0 0 0 1 1 1 0 0 1 0 1 1 0 0
 1 1 0 1 1 1 0 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 1 0 1 1 0 0 1 1 0 1 1 0 0 1 1
 1 0 1 0 1 0 0 1 1 0 1 0 1 1 1 1 1 0 0 0 0 1 0 1 0 1 1 1 1 0 0 1 0 1 0 0 0
 0 0 0 1 0 1 1 0 0 1 0 1 0 0 1 1 0 1 0 1 1 1 0 0 1 1 0 0 1 0 0 0 1 0 1 0 1
 1 0 1 0 1 0 1 1 0 1 0 0 1 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 1 0 0 1 0 1 0 0 0
 1 1 1 0 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1
 1 0 1 0 1 1 0 0 1 1 0 0 0 0 1 1 1 0 0 1 1 1 0 0 1 1 1 0 0 1 1 1 1 1 0 1 1
 1 1 0 1 0 0 1 1 0 1 1 0 1 0 1 1 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 1 0 1 0
 0 1 0 0 1 1 0 1 0 0 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 1 0 1 0 1 0 1
 1 1 1 0 1 0 1 0 1 1 1 0 

/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:588: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


executing  2  th time
executing  3  th time
executing  4  th time
executing  5  th time
executing  6  th time
executing  7  th time
executing  8  th time
executing  9  th time
executing  10  th time
executing  11  th time
executing  12  th time
executing  13  th time
executing  14  th time
executing  15  th time
executing  16  th time
executing  17  th time
executing  18  th time
executing  19  th time
executing  20  th time
executing  21  th time
executing  22  th time
executing  23  th time
executing  24  th time
executing  25  th time
executing  26  th time
executing  27  th time
executing  28  th time
executing  29  th time
executing  30  th time
executing  31  th time
executing  32  th time
executing  33  th time
epoch completed
epoch  1  has started
executing  1  th time
executing  2  th time
executing  3  th time
executing  4  th time
executing  5  th time
executing  6  th time
executing  7  th time
executing  8  th time
executing  9  th time
executing  10  th time
executing  11

In [ ]:
from sklearn.metrics import accuracy_score
pred=[]
vals=[]
indices=test_x.index
for i in list(test_x):
  new_texts =i
  n=list(test_x).index(i)
  inputs = tokenizer(new_texts, padding=True, truncation=True, return_tensors="pt")

  logits = model1(**inputs).logits
  predictions = logits.argmax(dim=1)
  print(predictions)
  if (predictions==0):
     pred.append([indices[n],'hs'])
     vals.append('hs')
  else:
     pred.append([indices[n],'nhs'])
     vals.append('nhs')
#accuracy = accuracy_score(test_y,pred)
#print(accuracy)
print(pred)
'''
if predictions.item()==0:
  print("hs")
else:
  print("nhs")
  '''

tensor([1])
tensor([1])
tensor([1])
tensor([0])
tensor([1])
tensor([0])
tensor([0])
tensor([0])
tensor([0])
tensor([0])
tensor([0])
tensor([0])
tensor([0])
tensor([0])
tensor([0])
tensor([1])
tensor([0])
tensor([1])
tensor([0])
tensor([0])
tensor([1])
tensor([1])
tensor([0])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([0])
tensor([0])
tensor([1])
tensor([0])
tensor([0])
tensor([1])
tensor([1])
tensor([0])
tensor([0])
tensor([0])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([0])
tensor([0])
tensor([0])
tensor([0])
tensor([1])
tensor([1])
tensor([0])
tensor([0])
tensor([1])
tensor([1])
tensor([0])
tensor([0])
tensor([1])
tensor([0])
tensor([0])
tensor([0])
tensor([1])
tensor([1])
tensor([1])
tensor([0])
tensor([1])
tensor([1])
tensor([0])
tensor([0])
tensor([0])
tensor([1])
tensor([1])
tensor([0])
tensor([1])
tensor([0])
tensor([1])
tensor([1])
tensor([0])
tensor([0])
tensor([1])
tensor([1])
tens

'\nif predictions.item()==0:\n  print("hs")\nelse:\n  print("nhs")\n  '

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score,recall_score

accuracy = accuracy_score(test_y,vals)
print("\nACCURACY: ",accuracy)
f1=f1_score(test_y,vals,pos_label='hs')
print("\nF1: ",f1)
precision=precision_score(test_y,vals,pos_label='hs')
print("\nPRECISION: ",precision)
recall=recall_score(test_y,vals,pos_label='hs')
print("\nRECALL: ",recall)


ACCURACY:  0.833729216152019

F1:  0.8325358851674641

PRECISION:  0.8571428571428571

RECALL:  0.8093023255813954


In [ ]:
data=pd.read_csv("/content/drive/MyDrive/hope_speech_testing.csv")
x=data['text']
pred=[]
indices=x.index
print(x,indices)
for i in list(x):
  new_texts =i
  n=list(x).index(i)
  inputs = tokenizer(new_texts, padding=True, truncation=True, return_tensors="pt")

  logits = model1(**inputs).logits
  predictions = logits.argmax(dim=1)
  print(predictions)
  if (predictions==0):
     pred.append([indices[n],'hs'])
  else:
     pred.append([indices[n],'nhs'])

0      iiiiii como amo a mis amigas soy totalmente ho...
1      ¿Qué necesidad tiene la gente de decirme que e...
2      si soy una inmigrante que legalmente puede vot...
3      Mis amigas :no soy lesbiana . Mis amigas borra...
4      🇦🇷🏳️‍⚧️La provincia de Buenos Aires  anunció e...
                             ...                        
395    Lo lamento mucho, cuanta rabia aquí estamos pa...
396    Oigan ahorita que lo pienso,cuando estaba más ...
397    🔍#Entrevista de  a , psicóloga, docente e inve...
398    Y seguimos con un racismo institucional muy gr...
399    'Puede ser una trampa'. El objetivo de esta in...
Name: text, Length: 400, dtype: object RangeIndex(start=0, stop=400, step=1)
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([1])
tensor([

In [ ]:
import csv

field=['id','category']

fpath='/content/drive/MyDrive/predictions.csv'

with open(fpath, 'w') as csvfile:

    csv_writer = csv.writer(csvfile)
    csv_writer.writerow(field)
    csv_writer.writerows(pred)


PRECISION AND RECALL CALCULATION FROM PREDICTIONS IN CSV FILE COMPARED WITH THE TEST DATA

In [ ]:
#precision and recall calculation for bert1
import pandas as pd
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

test_data=pd.read_csv("/content/drive/MyDrive/test_data.csv")
test_y=test_data['category']
test_topic_l=test_data[test_data['topic']=='lgtbi']
test_topic_o=test_data[test_data['topic']!='lgtbi']
test_y_l=test_topic_l['category']
test_y_o=test_topic_o['category']

test_y_l_index=test_y_l.index
print(test_y_l_index)

test_y_o_index=test_y_o.index
print(test_y_o_index)

#print(test_y)

pred_data=pd.read_csv('/content/drive/MyDrive/predictions-1(bert1-ducc).csv')
pred_y=pred_data['category']
#print(pred_y)

pred_y_l=pred_y[test_y_l_index]
pred_y_o=pred_y[test_y_o_index]


print("PRECISION IS: ",precision_score(test_y,pred_y,pos_label='hs'))
print("RECALL IS: ",recall_score(test_y,pred_y,pos_label='hs'))
print("ACCURACY IS: ",accuracy_score(test_y,pred_y))
f11=f1_score(test_y_l,pred_y_l,pos_label='hs')
f12=f1_score(test_y_o,pred_y_o,pos_label='hs')
print("F1 IS 1: ",f11)
print("F1 IS 2: ",f12)
print("average: ",(f11+f12)/2)

Index([  3,   4,   5,   7,   8,   9,  10,  12,  13,  17,
       ...
       378, 380, 382, 387, 390, 391, 393, 394, 395, 397],
      dtype='int64', length=200)
Index([  0,   1,   2,   6,  11,  14,  15,  16,  18,  20,
       ...
       383, 384, 385, 386, 388, 389, 392, 396, 398, 399],
      dtype='int64', length=200)
PRECISION IS:  0.75
RECALL IS:  0.15
ACCURACY IS:  0.55
F1 IS 1:  0.3333333333333333
F1 IS 2:  0.15789473684210525
average:  0.24561403508771928


In [ ]:
#precision and recall calculation for multinomialNB
import pandas as pd
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

test_data=pd.read_csv("/content/drive/MyDrive/test_data.csv")
test_y=test_data['category']
test_topic_l=test_data[test_data['topic']=='lgtbi']
test_topic_o=test_data[test_data['topic']!='lgtbi']
test_y_l=test_topic_l['category']
test_y_o=test_topic_o['category']

test_y_l_index=test_y_l.index
print(test_y_l_index)

test_y_o_index=test_y_o.index
print(test_y_o_index)

#print(test_y)

pred_data=pd.read_csv('/content/drive/MyDrive/predictions-3(multiNB-tfidf).csv')
pred_y=pred_data['category']
#print(pred_y)

pred_y_l=pred_y[test_y_l_index]
pred_y_o=pred_y[test_y_o_index]


print("PRECISION IS: ",precision_score(test_y,pred_y,pos_label='hs'))
print("RECALL IS: ",recall_score(test_y,pred_y,pos_label='hs'))
print("ACCURACY IS: ",accuracy_score(test_y,pred_y))
f11=f1_score(test_y_l,pred_y_l,pos_label='hs')
f12=f1_score(test_y_o,pred_y_o,pos_label='hs')
print("f1: ",f1_score(test_y,pred_y,pos_label='hs'))
print("F1 IS 1: ",f11)
print("F1 IS 2: ",f12)
print("average: ",(f11+f12)/2)

Index([  3,   4,   5,   7,   8,   9,  10,  12,  13,  17,
       ...
       378, 380, 382, 387, 390, 391, 393, 394, 395, 397],
      dtype='int64', length=200)
Index([  0,   1,   2,   6,  11,  14,  15,  16,  18,  20,
       ...
       383, 384, 385, 386, 388, 389, 392, 396, 398, 399],
      dtype='int64', length=200)
PRECISION IS:  0.5542168674698795
RECALL IS:  0.46
ACCURACY IS:  0.545
f1:  0.5027322404371585
F1 IS 1:  0.5775401069518717
F1 IS 2:  0.42458100558659223
average:  0.501060556269232


In [ ]:
#precision and recall calculation for log.reg
import pandas as pd
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

test_data=pd.read_csv("/content/drive/MyDrive/test_data.csv")
test_y=test_data['category']
print(test_y)

pred_data=pd.read_csv('/content/drive/MyDrive/predictions-4(logistic.reg).csv')
pred_y=pred_data['category']
print(pred_y)

print("PRECISION IS: ",precision_score(test_y,pred_y,pos_label='hs'))
print("RECALL IS: ",recall_score(test_y,pred_y,pos_label='hs'))
print("ACCURACY IS: ",accuracy_score(test_y,pred_y))
print("F1 IS: ",f1_score(test_y,pred_y,average='macro'))

0      nhs
1       hs
2      nhs
3      nhs
4      nhs
      ... 
395     hs
396     hs
397    nhs
398     hs
399     hs
Name: category, Length: 400, dtype: object
0       hs
1      nhs
2      nhs
3      nhs
4      nhs
      ... 
395     hs
396     hs
397    nhs
398    nhs
399    nhs
Name: category, Length: 400, dtype: object
PRECISION IS:  0.6559139784946236
RECALL IS:  0.305
ACCURACY IS:  0.5725
F1 IS:  0.5395520730254255


In [ ]:
#precision and recall calculation for logistic regression with macro f1
import pandas as pd
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

test_data=pd.read_csv("/content/drive/MyDrive/test_data.csv")
test_y=test_data['category']
test_topic_l=test_data[test_data['topic']=='lgtbi']
test_topic_o=test_data[test_data['topic']!='lgtbi']
test_y_l=test_topic_l['category']
test_y_o=test_topic_o['category']

test_y_l_index=test_y_l.index
print(test_y_l_index)

test_y_o_index=test_y_o.index
print(test_y_o_index)

#print(test_y)

pred_data=pd.read_csv('/content/drive/MyDrive/predictions-4(logistic.reg).csv')
pred_y=pred_data['category']
#print(pred_y)

pred_y_l=pred_y[test_y_l_index]
pred_y_o=pred_y[test_y_o_index]


print("PRECISION IS: ",precision_score(test_y,pred_y,pos_label='hs'))
print("RECALL IS: ",recall_score(test_y,pred_y,pos_label='hs'))
print("ACCURACY IS: ",accuracy_score(test_y,pred_y))
f11=f1_score(test_y_l,pred_y_l,pos_label='hs')
f12=f1_score(test_y_o,pred_y_o,pos_label='hs')
print("F1 IS 1: ",f11)
print("F1 IS 2: ",f12)
print("average: ",(f11+f12)/2)

Index([  3,   4,   5,   7,   8,   9,  10,  12,  13,  17,
       ...
       378, 380, 382, 387, 390, 391, 393, 394, 395, 397],
      dtype='int64', length=200)
Index([  0,   1,   2,   6,  11,  14,  15,  16,  18,  20,
       ...
       383, 384, 385, 386, 388, 389, 392, 396, 398, 399],
      dtype='int64', length=200)
PRECISION IS:  0.6559139784946236
RECALL IS:  0.305
ACCURACY IS:  0.5725
F1 IS 1:  0.4897959183673468
F1 IS 2:  0.3424657534246575
average:  0.4161308358960022
